name: Frontend Testing

on:
  pull_request:
    paths:
      - '.github/workflows/frontend.yml'
      - 'frontend/**'
      - 'common/**'
      - 'solr/**'
  push:
    branches:
      - '*___frontend'

jobs:

  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    strategy:
      matrix:
        java: [ 8, 11 ]

    services:
      db:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: archivesspace
          MYSQL_USER: as
          MYSQL_PASSWORD: as123
        ports:
          - 3307:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      solr:
        image: solr:8.11
        ports:
          - 8984:8983

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: temurin

    - uses: './.github/actions/bootstrap'
      with:
        backend: true
        frontend: true
        indexer: true

    - name: Copy solr config from workspace to solr service
      env:
        SOLR_ID: ${{ job.services.solr.id }}
      run: |
        docker cp solr $SOLR_ID:/solr_conf_from_repo

    - name: Create ArchivesSpace Solr core
      env:
        SOLR_ID: ${{ job.services.solr.id }}
      run: |
        docker exec --tty $SOLR_ID solr create_core -p 8983 -c archivesspace -d /solr_conf_from_repo

    - name: Run Frontend tests
      run: |
        ./build/run frontend:test
      env:
        ARCHIVESSPACE_VERSION: ${{ github.ref }}
        CAPYBARA_DEFAULT_MAX_WAIT_TIME: 10
        RSPEC_RETRIES: 3

    - name: Run deprecated tests
      run: |
        ./build/run frontend:selenium
      env:
        ARCHIVESSPACE_VERSION: ${{ github.ref }}

    - name: Dump the test database
      if: failure()
      env:
        DB_PORT: "3307"
      run: |
        mysqldump --host 127.0.0.1 --port $DB_PORT -uroot -proot archivesspace | gzip > ci_logs/archivesspace.sql.gz

    - name: Upload the ci logs
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: ci_logs
        path: ci_logs/*
