name: Frontend Testing

on:
  workflow_dispatch:
    inputs:
      java-version:
        description: Java version to run specs on
        required: true
        type: choice
        options:
          - '8'
          - '11'
        default: '11'

  workflow_call:
    inputs:
      java-version:
        description: Java version to run specs on
        required: true
        type: string
        default: '11'

  pull_request:
    paths:
      - '.github/workflows/frontend.yml'
      - '.github/workflows/common-frontend.yml'
      - 'frontend/**'
      - 'common/**'
      - 'solr/**'

jobs:
  frontend_a-c:
    name: a-c_Java_v${{ inputs.java-version || 11 }} # https://archivesspace.atlassian.net/browse/ANW-2022
    uses: ./.github/workflows/common-frontend.yml
    secrets: inherit
    with:
      run-cmd: |
        ./build/run frontend:test -Dpattern="spec/features/[a-c]*_spec.rb"
      name: a-c
      java-version: ${{ inputs.java-version || 11 }}

  frontend_d-l:
    name: d-l_Java_v${{ inputs.java-version || 11 }}
    uses: ./.github/workflows/common-frontend.yml
    secrets: inherit
    with:
      run-cmd: |
        ./build/run frontend:test -Dpattern="spec/features/[d-l]*_spec.rb"
      name: d-l
      java-version: ${{ inputs.java-version || 11 }}

  frontend_m-r:
    name: m-r_Java_v${{ inputs.java-version || 11 }}
    uses: ./.github/workflows/common-frontend.yml
    secrets: inherit
    with:
      run-cmd: |
        ./build/run frontend:test -Dpattern="spec/features/[m-r]*_spec.rb"
      name: m-r
      java-version: ${{ inputs.java-version || 11 }}

  frontend_s-z:
    name: s-z_Java_v${{ inputs.java-version || 11 }}
    uses: ./.github/workflows/common-frontend.yml
    secrets: inherit
    with:
      run-cmd: |
        ./build/run frontend:test -Dpattern="spec/features/[s-z]*_spec.rb"
      name: s-z
      java-version: ${{ inputs.java-version || 11 }}
