name: Public Testing

on:
  pull_request:
    paths:
      - '.github/workflows/public.yml'
      - 'public/**'
      - 'common/**'
      - 'solr/**'
      - 'indexer/**'
  push:
    branches:
      - '*___public'

jobs:

  public-tests:
    name: Public Tests
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    strategy:
      matrix:
        java: [ 8, 11 ]

    services:
      db:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: archivesspace
          MYSQL_USER: as
          MYSQL_PASSWORD: as123
        ports:
          - 3307:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      solr:
        image: solr:8.11
        ports:
          - 8984:8983

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: temurin

    - uses: './.github/actions/bootstrap'
      with:
        backend: true
        public: true
        indexer: true

    - name: Copy solr config from workspace to solr service
      env:
        SOLR_ID: ${{ job.services.solr.id }}
      run: |
        docker cp ./solr $SOLR_ID:/solr_conf_from_repo

    - name: Create ArchivesSpace Solr core
      env:
        SOLR_ID: ${{ job.services.solr.id }}
      run: |
        docker exec --tty $SOLR_ID solr create_core -p 8983 -c archivesspace -d /solr_conf_from_repo

    - name: Run Public tests
      run: |
        ./build/run public:test
      env:
        ARCHIVESSPACE_VERSION: ${{ github.ref }}
        RSPEC_RETRIES: 2

    - name: Upload the ci logs
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: ci_logs
        path: ci_logs/*
